apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r2w6g88xy-java-springboot 
  janus-idp.io/tekton: r2w6g88xy-java-springboot
  backstage.io/kubernetes-id: r2w6g88xy-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r2w6g88xy-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml